java_library(
    name = "ras",
    srcs = ["Rasmalai.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/query/ingredients:salt",
        "//src/main/java/com/query/ingredients:tomato",
    ],
)

java_library(
    name = "hcp",
    srcs = ["HoneyChilliPotato.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/query/ingredients:salt",
        "//src/main/java/com/query/ingredients:tomato"
    ],
)