java_library(
    name = "tomato",
    srcs = ["Tomato.java"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "salt",
    srcs = ["Salt.java"],
    visibility = ["//visibility:public"],
)