java_binary(
    name = "review",
    srcs = [
        "Review.java",
    ],
    main_class = "com.query.reviews.Review",
    tags = ["hcp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/query/customers:gaurav",
    ],
)