java_library(
    name = "chef",
    srcs = [
        "Chef.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/query/dishes:hcp",
        "//src/main/java/com/query/dishes:ras",
    ],
)

java_library(
    name = "udupi",
    srcs = [
        "Udupi.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":chef",
    ],
)